name: Artifact Sample

on : [push]

jobs: 
  upload_artifact:
    name: Upload artifact
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: | 
        echo hello > sample_file.txt
    - name: Upload output file
      uses: actions/upload-artifact@v3.1.0
      with:
        name: sample_file.txt
        path: sample_file.txt
  download_artifact:
    name: Download artifact
    runs-on: ubuntu-latest
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: sample_file.txt
        needs: upload_artifact
