name: Create Artifact

on : [push]

jobs: 
  create_artifact:
    name: Create Artifact
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: | 
        echo hello > sample_file.txt
    - name: Upload output file
      uses: actions/upload-artifact@v3.1.0
      with:
        name: sample_file.txt
        path: sample_file.txt
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: sample_text.txt
